config/routes.rb
Rails.application.routes.draw do
  resources :samples
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dummy.rb
class Dummy < ApplicationRecord

    def check_age_class?
        self.age.class.to_s == 'Integer'
    end
end

app/models/sample.rb
class Sample < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: %i[ show edit update destroy ]

  # GET /samples or /samples.json
  def index
    # @samples = Sample.all
    render json: { status: 'online' }, status: 200
  end

  # GET /samples/1 or /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples or /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to sample_url(@sample), notice: "Sample was successfully created." }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1 or /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to sample_url(@sample), notice: "Sample was successfully updated." }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1 or /samples/1.json
  def destroy
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to samples_url, notice: "Sample was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sample_params
      params.fetch(:sample, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rspec</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/samples/_form.html.erb
<%= form_with(model: sample) do |form| %>
  <% if sample.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
        <% sample.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/samples/_sample.html.erb
<div id="<%= dom_id sample %>">
</div>

app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= render "form", sample: @sample %>

<br>

<div>
  <%= link_to "Show this sample", @sample %> |
  <%= link_to "Back to samples", samples_path %>
</div>

app/views/samples/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Samples</h1>

<div id="samples">
  <% @samples.each do |sample| %>
    <%= render sample %>
    <p>
      <%= link_to "Show this sample", sample %>
    </p>
  <% end %>
</div>

<%= link_to "New sample", new_sample_path %>

app/views/samples/new.html.erb
<h1>New sample</h1>

<%= render "form", sample: @sample %>

<br>

<div>
  <%= link_to "Back to samples", samples_path %>
</div>

app/views/samples/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sample %>

<div>
  <%= link_to "Edit this sample", edit_sample_path(@sample) %> |
  <%= link_to "Back to samples", samples_path %>

  <%= button_to "Destroy this sample", @sample, method: :delete %>
</div>